# Generated by Django 4.2.4 on 2023-08-31 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_info', '0001_initial'),
        ('academic_degree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdegree',
            name='iin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_degree', to='general_info.generalinfo'),
        ),
    ]
