# Generated by Django 4.2.4 on 2023-10-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_degree', '0002_alter_academicdegree_iin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicdegree',
            old_name='diploma_number',
            new_name='diploma_number_academic',
        ),
        migrations.RenameField(
            model_name='academicdegree',
            old_name='education_place',
            new_name='education_place_academic',
        ),
    ]
