# Generated by Django 4.2.4 on 2023-08-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_status', models.CharField(blank=True, max_length=255, null=True)),
                ('departament', models.CharField(blank=True, max_length=255, null=True)),
                ('jposition', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('iin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='general_info.generalinfo')),
            ],
            options={
                'db_table': 'personal_data',
            },
        ),
    ]
