# Generated by Django 4.2.4 on 2023-08-23 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos')),
                ('iin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='general_info.generalinfo')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
