# Generated by Django 4.2.4 on 2023-08-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_info', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(blank=True, max_length=255, null=True)),
                ('education_place', models.CharField(blank=True, max_length=255, null=True)),
                ('education_date_in', models.DateField(null=True)),
                ('education_date_out', models.DateField(null=True)),
                ('education_speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('diploma_number', models.CharField(blank=True, max_length=255, null=True)),
                ('iin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='general_info.generalinfo')),
            ],
            options={
                'db_table': 'education',
            },
        ),
    ]
