# Generated by Django 4.2.4 on 2023-08-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military_rank', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.DateField(null=True)),
                ('type_of_receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('iin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_ranks', to='general_info.generalinfo')),
            ],
            options={
                'db_table': 'military_rank',
            },
        ),
    ]
