# Generated by Django 4.2.4 on 2023-10-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghistory',
            old_name='jposition',
            new_name='jposition_work',
        ),
    ]
