# Generated by Django 4.2.4 on 2023-10-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working_history', '0002_rename_jposition_workinghistory_jposition_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghistory',
            old_name='departament',
            new_name='departament_work',
        ),
    ]
