# Generated by Django 4.2.4 on 2023-10-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigation_retrieval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigationretrieval',
            old_name='order_date',
            new_name='order_date_investigation',
        ),
        migrations.RenameField(
            model_name='investigationretrieval',
            old_name='order_type',
            new_name='order_type_investigation',
        ),
    ]
