# Generated by Django 4.2.4 on 2023-08-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_doc_numb', models.CharField(blank=True, max_length=255, null=True)),
                ('sick_doc_date', models.DateField(null=True)),
                ('iin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_leaves', to='general_info.generalinfo')),
            ],
            options={
                'db_table': 'sick_leaves',
            },
        ),
    ]
