# Generated by Django 4.2.4 on 2023-08-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_info', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation_result', models.CharField(blank=True, max_length=255, null=True)),
                ('last_attestation_date', models.DateField(null=True)),
                ('next_attestation_date', models.DateField(null=True)),
                ('iin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='general_info.generalinfo')),
            ],
            options={
                'db_table': 'attestation',
            },
        ),
    ]
