# Generated by Django 4.2.4 on 2023-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('birth_country', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_region', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('id_numbers', models.CharField(blank=True, max_length=255, null=True)),
                ('id_from', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('resid_country', models.CharField(blank=True, max_length=255, null=True)),
                ('resid_city', models.CharField(blank=True, max_length=255, null=True)),
                ('resid_region', models.CharField(blank=True, max_length=255, null=True)),
                ('pin', models.CharField(blank=True, max_length=255, null=True)),
                ('id_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'general_info',
            },
        ),
    ]
