# Generated by Django 4.2.4 on 2023-09-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_info', '0003_alter_generalinfo_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='birth_oblast',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
